name: ci
on:
  push:
    branches:
      - 4.1
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11
          - java: 25
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: actions/checkout@v7
    - uses: coursier/cache-action@v8
    - run: |
        export TZ=Australia/Canberra
        ./sbt -v scalafmtSbtCheck scalafmtCheckAll mimaReportBinaryIssues test
