name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 17
          - java: 25
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: actions/checkout@v6
    - uses: coursier/cache-action@v8
    - run: |
        export TZ=Australia/Canberra
        ./sbt --server -v scalafmtSbtCheck scalafmtCheckAll test
  latest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: 25
        distribution: zulu
    - uses: actions/checkout@v6
    - uses: coursier/cache-action@v8
    - id: scala_3_version
      run: echo "value=$(cat .github/scala_3_latest.txt)" >> $GITHUB_OUTPUT
    - run: |
        export TZ=Australia/Canberra
        ./sbt --server -v "++ ${{ steps.scala_3_version.outputs.value }}!" rootJVM3/test
